version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: y4l
      POSTGRES_PASSWORD: y4l_password_change_me
      POSTGRES_DB: yours4live
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    restart: unless-stopped

  media:
    image: alfg/nginx-rtmp
    container_name: y4l-media
    restart: unless-stopped
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./media/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./media/hls:/opt/data/hls
    entrypoint: ["nginx"]
    command: ["-g", "daemon off;"]

  proxy:
    image: nginx:alpine
    container_name: y4l-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - admin
      - api
      - media

  api:
    build: ./services/api
    env_file: .env
    depends_on:
      - db
      - redis
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    ports:
      - "4000:4000"
    restart: unless-stopped

  web:
    build: ./apps/web
    env_file: .env
    depends_on:
      - api
    ports:
      - "3001:3001"
    restart: unless-stopped

  admin:
    build: ./apps/admin
    env_file: .env
    depends_on:
      - api
    ports:
      - "3002:3002"
    restart: unless-stopped

volumes:
  pgdata:

